version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-microservice-car-reserve
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 1234
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27033:27017"
    volumes:
      - ./mongo-volume:/data/db